-- MySQL Script generated by MySQL Workbench
-- mié 27 may 2026 21:20:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cultura
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cultura` ;

-- -----------------------------------------------------
-- Schema cultura
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cultura` DEFAULT CHARACTER SET utf8 ;
USE `cultura` ;

-- -----------------------------------------------------
-- Table `cultura`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`USUARIOS` (
  `idUSUARIO` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `DNI` VARCHAR(45) NOT NULL,
  `genero` ENUM('F', 'M', 'X') NOT NULL DEFAULT 'F',
  `fechaNacimiento` DATE NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(255) NOT NULL DEFAULT 'sha(256)',
  `fechaRegistro` DATETIME NOT NULL,
  `rol` ENUM('USUARIO', 'MODERADOR', 'ADMIN') NOT NULL,
  `estado` ENUM('A', 'P', 'I') NOT NULL DEFAULT 'P',
  PRIMARY KEY (`idUSUARIO`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultura`.`CATEGORIAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`CATEGORIAS` (
  `idCATEGORIA` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` ENUM('A', 'I') NOT NULL,
  PRIMARY KEY (`idCATEGORIA`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultura`.`UBICACIONES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`UBICACIONES` (
  `idUBICACION` INT NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `departamento` VARCHAR(45) NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(205) NOT NULL,
  `latitud` DECIMAL(10,8) NOT NULL,
  `longitud` DECIMAL(11,8) NOT NULL,
  `esPublica` TINYINT NOT NULL,
  PRIMARY KEY (`idUBICACION`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultura`.`ACTORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`ACTORES` (
  `idACTOR` INT NOT NULL,
  `idCATEGORIA` INT NOT NULL,
  `idUSUARIODueño` INT NOT NULL,
  `idUBICACION` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `CUIT` CHAR(11) NOT NULL,
  `tipoActor` ENUM('INDIVIDUO', 'COLECTIVO', 'ESPACIO') NOT NULL,
  `fechaCreacion` DATETIME NOT NULL,
  PRIMARY KEY (`idACTOR`, `idCATEGORIA`, `idUSUARIODueño`, `idUBICACION`),
  INDEX `fk_ACTORES_USUARIOS1_idx` (`idUSUARIODueño` ASC) VISIBLE,
  INDEX `fk_ACTORES_CATEGORIAS1_idx` (`idCATEGORIA` ASC) VISIBLE,
  INDEX `fk_ACTORES_UBICACIONES1_idx` (`idUBICACION` ASC) VISIBLE,
  CONSTRAINT `fk_ACTORES_USUARIOS1`
    FOREIGN KEY (`idUSUARIODueño`)
    REFERENCES `cultura`.`USUARIOS` (`idUSUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ACTORES_CATEGORIAS1`
    FOREIGN KEY (`idCATEGORIA`)
    REFERENCES `cultura`.`CATEGORIAS` (`idCATEGORIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ACTORES_UBICACIONES1`
    FOREIGN KEY (`idUBICACION`)
    REFERENCES `cultura`.`UBICACIONES` (`idUBICACION`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultura`.`EVENTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`EVENTOS` (
  `idEVENTO` INT NOT NULL,
  `idUBICACION` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `fechaInicio` DATETIME NOT NULL,
  `fechaFin` DATETIME NOT NULL,
  `estado` ENUM('A', 'I') NOT NULL,
  `esAnual` TINYINT NOT NULL,
  `fechaCreacion` DATETIME NOT NULL,
  PRIMARY KEY (`idEVENTO`),
  INDEX `fk_EVENTOS_UBICACIONES1_idx` (`idUBICACION` ASC) VISIBLE,
  CONSTRAINT `fk_EVENTOS_UBICACIONES1`
    FOREIGN KEY (`idUBICACION`)
    REFERENCES `cultura`.`UBICACIONES` (`idUBICACION`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultura`.`INTEGRANTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`INTEGRANTES` (
  `USUARIOS_idUSUARIO` INT NOT NULL,
  `ACTORES_idACTORES` INT NOT NULL,
  `rol` VARCHAR(45) NULL,
  PRIMARY KEY (`USUARIOS_idUSUARIO`, `ACTORES_idACTORES`),
  INDEX `fk_USUARIOS_has_ACTORES_ACTORES1_idx` (`ACTORES_idACTORES` ASC) VISIBLE,
  INDEX `fk_USUARIOS_has_ACTORES_USUARIOS_idx` (`USUARIOS_idUSUARIO` ASC) VISIBLE,
  CONSTRAINT `fk_USUARIOS_has_ACTORES_USUARIOS`
    FOREIGN KEY (`USUARIOS_idUSUARIO`)
    REFERENCES `cultura`.`USUARIOS` (`idUSUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIOS_has_ACTORES_ACTORES1`
    FOREIGN KEY (`ACTORES_idACTORES`)
    REFERENCES `cultura`.`ACTORES` (`idACTOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultura`.`ACTORESEVENTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`ACTORESEVENTOS` (
  `EVENTOS_idEVENTO` INT NOT NULL,
  `ACTORES_idACTOR` INT NOT NULL,
  PRIMARY KEY (`EVENTOS_idEVENTO`, `ACTORES_idACTOR`),
  INDEX `fk_EVENTOS_has_ACTORES_ACTORES1_idx` (`ACTORES_idACTOR` ASC) VISIBLE,
  INDEX `fk_EVENTOS_has_ACTORES_EVENTOS1_idx` (`EVENTOS_idEVENTO` ASC) VISIBLE,
  CONSTRAINT `fk_EVENTOS_has_ACTORES_EVENTOS1`
    FOREIGN KEY (`EVENTOS_idEVENTO`)
    REFERENCES `cultura`.`EVENTOS` (`idEVENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EVENTOS_has_ACTORES_ACTORES1`
    FOREIGN KEY (`ACTORES_idACTOR`)
    REFERENCES `cultura`.`ACTORES` (`idACTOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultura`.`ITEMSPORTAFOLIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`ITEMSPORTAFOLIO` (
  `idITEM` INT NOT NULL,
  `ACTORES_idACTOR` INT NOT NULL,
  `tipo` ENUM('IMAGEN', 'VIDEO', 'AUDIO', 'DOCUMENTO', 'LINK') NOT NULL,
  `url` VARCHAR(245) NULL,
  `orden` INT NULL,
  `descripcion` MEDIUMTEXT NULL,
  PRIMARY KEY (`idITEM`),
  INDEX `fk_ITEMSPORTAFOLIO_ACTORES1_idx` (`ACTORES_idACTOR` ASC) VISIBLE,
  CONSTRAINT `fk_ITEMSPORTAFOLIO_ACTORES1`
    FOREIGN KEY (`ACTORES_idACTOR`)
    REFERENCES `cultura`.`ACTORES` (`idACTOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultura`.`CAMPOSFORMULARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`CAMPOSFORMULARIOS` (
  `idCAMPO` INT NOT NULL,
  `CATEGORIAS_idCATEGORIA` INT NOT NULL,
  `tipoDato` VARCHAR(45) NOT NULL,
  `esPublico` TINYINT NOT NULL,
  `obligatorio` TINYINT NOT NULL,
  `orden` TINYINT NOT NULL,
  `pregunta` LONGTEXT NOT NULL,
  PRIMARY KEY (`idCAMPO`),
  INDEX `fk_CAMPOSFORMULARIOS_CATEGORIAS1_idx` (`CATEGORIAS_idCATEGORIA` ASC) VISIBLE,
  CONSTRAINT `fk_CAMPOSFORMULARIOS_CATEGORIAS1`
    FOREIGN KEY (`CATEGORIAS_idCATEGORIA`)
    REFERENCES `cultura`.`CATEGORIAS` (`idCATEGORIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultura`.`RESPUESTASFORMULARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`RESPUESTASFORMULARIOS` (
  `idRESPUESTA` INT NOT NULL,
  `ACTORES_idACTOR` INT NOT NULL,
  `CAMPOSFORMULARIOS_idCAMPO` INT NOT NULL,
  `valor` JSON NULL,
  PRIMARY KEY (`idRESPUESTA`),
  INDEX `fk_RESPUESTASFORMULARIOS_ACTORES1_idx` (`ACTORES_idACTOR` ASC) VISIBLE,
  INDEX `fk_RESPUESTASFORMULARIOS_CAMPOSFORMULARIOS1_idx` (`CAMPOSFORMULARIOS_idCAMPO` ASC) INVISIBLE,
  UNIQUE INDEX `un-actorcampo` (`ACTORES_idACTOR` ASC, `CAMPOSFORMULARIOS_idCAMPO` ASC) VISIBLE,
  CONSTRAINT `fk_RESPUESTASFORMULARIOS_ACTORES1`
    FOREIGN KEY (`ACTORES_idACTOR`)
    REFERENCES `cultura`.`ACTORES` (`idACTOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RESPUESTASFORMULARIOS_CAMPOSFORMULARIOS1`
    FOREIGN KEY (`CAMPOSFORMULARIOS_idCAMPO`)
    REFERENCES `cultura`.`CAMPOSFORMULARIOS` (`idCAMPO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultura`.`MODERADORESCATEGORIAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`MODERADORESCATEGORIAS` (
  `USUARIOS_idUSUARIO` INT NOT NULL,
  `CATEGORIAS_idCATEGORIA` INT NOT NULL,
  PRIMARY KEY (`USUARIOS_idUSUARIO`, `CATEGORIAS_idCATEGORIA`),
  INDEX `fk_USUARIOS_has_CATEGORIAS_CATEGORIAS1_idx` (`CATEGORIAS_idCATEGORIA` ASC) VISIBLE,
  INDEX `fk_USUARIOS_has_CATEGORIAS_USUARIOS1_idx` (`USUARIOS_idUSUARIO` ASC) VISIBLE,
  CONSTRAINT `fk_USUARIOS_has_CATEGORIAS_USUARIOS1`
    FOREIGN KEY (`USUARIOS_idUSUARIO`)
    REFERENCES `cultura`.`USUARIOS` (`idUSUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIOS_has_CATEGORIAS_CATEGORIAS1`
    FOREIGN KEY (`CATEGORIAS_idCATEGORIA`)
    REFERENCES `cultura`.`CATEGORIAS` (`idCATEGORIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
