-- MySQL Script generated by MySQL Workbench
-- Sat Jun 27 12:17:42 2026
-- Model: cultura    Version: 1.0.1

-- Authors: Cesar Ezequiel Herrera, Leandro Murillo
-- Description:
-- 1.0.1 - Se estableció una convención uniforme para las tablas, columnas, claves e índices

-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cultura
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cultura` ;

-- -----------------------------------------------------
-- Schema cultura
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cultura` DEFAULT CHARACTER SET utf8 ;
USE `cultura` ;

-- -----------------------------------------------------
-- Table `cultura`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`Usuarios` (
  `idUsuario` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `dni` VARCHAR(45) NOT NULL,
  `genero` ENUM('F', 'M', 'X') NOT NULL DEFAULT 'F',
  `fechaNacimiento` DATE NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(255) NOT NULL DEFAULT 'sha(256)',
  `fechaRegistro` DATETIME NOT NULL,
  `rol` ENUM('USUARIO', 'MODERADOR', 'ADMIN') NOT NULL,
  `estado` ENUM('A', 'P', 'I') NOT NULL DEFAULT 'P',
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `uq_Usuarios_email` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultura`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`Categorias` (
  `idCategoria` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` ENUM('A', 'I') NOT NULL,
  PRIMARY KEY (`idCategoria`),
  UNIQUE INDEX `uq_Categorias_nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultura`.`Ubicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`Ubicaciones` (
  `idUbicacion` INT NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `departamento` VARCHAR(45) NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(205) NOT NULL,
  `latitud` DECIMAL(10,8) NOT NULL,
  `longitud` DECIMAL(11,8) NOT NULL,
  `esPublica` TINYINT NOT NULL,
  PRIMARY KEY (`idUbicacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultura`.`Actores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`Actores` (
  `idActor` INT NOT NULL,
  `idCategoria` INT NOT NULL,
  `idUsuarioDueño` INT NOT NULL,
  `idUbicacion` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `cuit` CHAR(11) NOT NULL,
  `tipoActor` ENUM('INDIVIDUO', 'COLECTIVO', 'ESPACIO') NOT NULL,
  `fechaCreacion` DATETIME NOT NULL,
  PRIMARY KEY (`idActor`, `idCategoria`, `idUsuarioDueño`, `idUbicacion`),
  INDEX `fk_Actores_Usuarios_idk` (`idUsuarioDueño` ASC) VISIBLE,
  INDEX `fk_Actores_Categorias_idk` (`idCategoria` ASC) VISIBLE,
  INDEX `fk_Actores_Ubicaciones_idk` (`idUbicacion` ASC) VISIBLE,
  CONSTRAINT `fk_Actores_Usuarios`
    FOREIGN KEY (`idUsuarioDueño`)
    REFERENCES `cultura`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actores_Categorias`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `cultura`.`Categorias` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actores_Ubicaciones`
    FOREIGN KEY (`idUbicacion`)
    REFERENCES `cultura`.`Ubicaciones` (`idUbicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultura`.`Eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`Eventos` (
  `idEvento` INT NOT NULL,
  `idUbicacion` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `fechaInicio` DATETIME NOT NULL,
  `fechaFin` DATETIME NOT NULL,
  `estado` ENUM('A', 'I') NOT NULL,
  `esAnual` TINYINT NOT NULL,
  `fechaCreacion` DATETIME NOT NULL,
  PRIMARY KEY (`idEvento`),
  INDEX `fk_Eventos_Ubicaciones_idx` (`idUbicacion` ASC) VISIBLE,
  CONSTRAINT `fk_Eventos_Ubicaciones`
    FOREIGN KEY (`idUbicacion`)
    REFERENCES `cultura`.`Ubicaciones` (`idUbicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultura`.`Integrantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`Integrantes` (
  `idUsuario` INT NOT NULL,
  `idActor` INT NOT NULL,
  `rol` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`, `idActor`),
  INDEX `fk_Integrantes_Actores_idx` (`idActor` ASC) VISIBLE,
  INDEX `fk_Integrantes_Usuarios_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Integrantes_Usuarios`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `cultura`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Integrantes_Actores`
    FOREIGN KEY (`idActor`)
    REFERENCES `cultura`.`Actores` (`idActor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultura`.`ActoresEventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`ActoresEventos` (
  `idEvento` INT NOT NULL,
  `idActor` INT NOT NULL,
  PRIMARY KEY (`idEvento`, `idActor`),
  INDEX `fk_ActoresEventos_Actores_idx` (`idActor` ASC) VISIBLE,
  INDEX `fk_ActoresEventos_Eventos_idx` (`idEvento` ASC) VISIBLE,
  CONSTRAINT `fk_ActoresEventos_Eventos`
    FOREIGN KEY (`idEvento`)
    REFERENCES `cultura`.`Eventos` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ActoresEventos_Actores`
    FOREIGN KEY (`idActor`)
    REFERENCES `cultura`.`Actores` (`idActor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultura`.`ItemsPortafolio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`ItemsPortafolio` (
  `idItem` INT NOT NULL,
  `idActor` INT NOT NULL,
  `tipo` ENUM('IMAGEN', 'VIDEO', 'AUDIO', 'DOCUMENTO', 'LINK') NOT NULL,
  `url` VARCHAR(245) NULL,
  `orden` INT NULL,
  `descripcion` MEDIUMTEXT NULL,
  PRIMARY KEY (`idItem`),
  INDEX `fk_ItemsPortafolio_Actores_idx` (`idActor` ASC) VISIBLE,
  CONSTRAINT `fk_ItemsPortafolio_Actores`
    FOREIGN KEY (`idActor`)
    REFERENCES `cultura`.`Actores` (`idActor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultura`.`CamposFormularios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`CamposFormularios` (
  `idCampo` INT NOT NULL,
  `idCategoria` INT NOT NULL,
  `tipoDato` VARCHAR(45) NOT NULL,
  `esPublico` TINYINT NOT NULL,
  `obligatorio` TINYINT NOT NULL,
  `orden` TINYINT NOT NULL,
  `pregunta` LONGTEXT NOT NULL,
  PRIMARY KEY (`idCampo`),
  INDEX `fk_CamposFormularios_Categorias_idx` (`idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_CamposFormularios_Categorias`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `cultura`.`Categorias` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultura`.`RespuestasFormularios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`RespuestasFormularios` (
  `idRespuesta` INT NOT NULL,
  `idActor` INT NOT NULL,
  `idCampo` INT NOT NULL,
  `valor` JSON NULL,
  PRIMARY KEY (`idRespuesta`),
  INDEX `fk_RespuestasFormularios_Actores_idx` (`idActor` ASC) VISIBLE,
  INDEX `fk_RespuestasFormularios_CamposFormularios_idx` (`idCampo` ASC) VISIBLE,
  UNIQUE INDEX `uq_RespuestasFormulario_idActor_idCampo` (`idActor` ASC, `idCampo` ASC) VISIBLE,
  CONSTRAINT `fk_RespuestasFormularios_Actores`
    FOREIGN KEY (`idActor`)
    REFERENCES `cultura`.`Actores` (`idActor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RespuestasFormularios_CamposFormularios`
    FOREIGN KEY (`idCampo`)
    REFERENCES `cultura`.`CamposFormularios` (`idCampo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultura`.`ModeradoresCategorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`ModeradoresCategorias` (
  `idUsuario` INT NOT NULL,
  `idCategoria` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `idCategoria`),
  INDEX `fk_ModeradoresCategorias_Categorias_idx` (`idCategoria` ASC) VISIBLE,
  INDEX `fk_ModeradoresCategorias_Usuarios_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_ModeradoresCategorias_Usuarios`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `cultura`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ModeradoresCategorias_Categorias`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `cultura`.`Categorias` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
