-- MySQL Script generated by MySQL Workbench
-- Thu Jul  9 22:17:33 2026
-- Model: cultura    Version: 1.2.1

-- Authors: Cesar Ezequiel Herrera, Leandro Murillo

-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cultura
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cultura` ;

-- -----------------------------------------------------
-- Schema cultura
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cultura` DEFAULT CHARACTER SET utf8 ;
USE `cultura` ;

-- -----------------------------------------------------
-- Table `cultura`.`ActividadesArca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`ActividadesArca` (
  `codigo` CHAR(6) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `descripcion_UNIQUE` (`descripcion` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultura`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`Usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `actividadesArcaCodigo` CHAR(6) NULL COMMENT 'Si es NULL, no está registrado.',
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `genero` ENUM('F', 'M', 'X') NOT NULL DEFAULT 'F',
  `fechaNacimiento` DATE NOT NULL,
  `nacionalidad` VARCHAR(45) NOT NULL,
  `email` VARCHAR(99) NOT NULL,
  `contraseña` VARCHAR(255) NOT NULL DEFAULT 'sha(256)',
  `fechaRegistro` DATETIME NOT NULL,
  `rol` ENUM('USUARIO', 'MODERADOR', 'ADMIN') NOT NULL,
  `estado` ENUM('A', 'P', 'I') NOT NULL DEFAULT 'P',
  `CUIL` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `uq_Usuarios_email` (`email` ASC) VISIBLE,
  INDEX `fk_Usuarios_actividades_arca_idx` (`actividadesArcaCodigo` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_actividades_arca`
    FOREIGN KEY (`actividadesArcaCodigo`)
    REFERENCES `cultura`.`ActividadesArca` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultura`.`Ubicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`Ubicaciones` (
  `idUbicacion` INT NOT NULL AUTO_INCREMENT,
  `provincia` VARCHAR(45) NOT NULL,
  `departamento` VARCHAR(45) NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(205) NOT NULL,
  `latitud` DECIMAL(10,8) NOT NULL,
  `longitud` DECIMAL(11,8) NOT NULL,
  `esPublica` TINYINT NOT NULL,
  PRIMARY KEY (`idUbicacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultura`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`Categorias` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` ENUM('A', 'I') NOT NULL,
  PRIMARY KEY (`idCategoria`),
  UNIQUE INDEX `uq_Categorias_nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultura`.`Subcategorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`Subcategorias` (
  `idSubcategoria` INT NOT NULL,
  `idCategoria` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idSubcategoria`, `idCategoria`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC, `idCategoria` ASC) VISIBLE,
  INDEX `FK_Categorias_idCategoria1_idx` (`idCategoria` ASC) VISIBLE,
  CONSTRAINT `FK_Categorias_idCategoria1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `cultura`.`Categorias` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultura`.`Actores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`Actores` (
  `idActor` INT NOT NULL AUTO_INCREMENT,
  `idSubcategoria` INT NOT NULL,
  `idCategoria` INT NOT NULL,
  `idUbicacion` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
  `fotoPerfilUrl` VARCHAR(245) NULL,
  `cuit` CHAR(11) NOT NULL,
  `tipoActor` ENUM('INDIVIDUO', 'COLECTIVO', 'ESPACIO') NOT NULL,
  `fechaCreacion` DATETIME NOT NULL,
  `estado` ENUM('A', 'P', 'I') NOT NULL,
  PRIMARY KEY (`idActor`),
  INDEX `fk_Actores_Ubicaciones1_idx` (`idUbicacion` ASC) VISIBLE,
  INDEX `fk_Actores_Subcategorias1_idx` (`idSubcategoria` ASC, `idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Actores_Ubicaciones1`
    FOREIGN KEY (`idUbicacion`)
    REFERENCES `cultura`.`Ubicaciones` (`idUbicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actores_Subcategorias1`
    FOREIGN KEY (`idSubcategoria` , `idCategoria`)
    REFERENCES `cultura`.`Subcategorias` (`idSubcategoria` , `idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultura`.`Eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`Eventos` (
  `idEvento` INT NOT NULL AUTO_INCREMENT,
  `idActor` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `fechaCreacion` DATETIME NOT NULL,
  `estado` ENUM('A', 'I') NOT NULL,
  PRIMARY KEY (`idEvento`),
  INDEX `fk_Eventos_Actores1_idx` (`idActor` ASC) VISIBLE,
  CONSTRAINT `fk_Eventos_Actores1`
    FOREIGN KEY (`idActor`)
    REFERENCES `cultura`.`Actores` (`idActor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultura`.`ItemsPortafolio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`ItemsPortafolio` (
  `idItem` INT NOT NULL AUTO_INCREMENT,
  `idActor` INT NOT NULL,
  `tipo` ENUM('IMAGEN', 'LINK') NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL COMMENT 'Ejemplo: \"Ultimo recital del Indio (2000). El pogo más grande de la historia\"\n               \"Enlace a Facebook:\"',
  `url` VARCHAR(245) NULL,
  `orden` INT NULL,
  PRIMARY KEY (`idItem`),
  INDEX `fk_ItemsPortafolio_Actores1_idx` (`idActor` ASC) VISIBLE,
  CONSTRAINT `fk_ItemsPortafolio_Actores1`
    FOREIGN KEY (`idActor`)
    REFERENCES `cultura`.`Actores` (`idActor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultura`.`CamposFormulario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`CamposFormulario` (
  `idCampo` INT NOT NULL AUTO_INCREMENT,
  `pregunta` VARCHAR(500) NOT NULL,
  `tipoDato` ENUM('TEXTO', 'NUMERO', 'BOOLEANO', 'FECHA', 'URL', 'EMAIL', 'TELEFONO', 'OPCION_UNICA', 'OPCION_MULTIPLE') NOT NULL COMMENT 'tipoDato ENUM(\n        \'TEXTO\',\n        \'NUMERO\',\n        \'BOOLEANO\',\n        \'FECHA\',\n        \'URL\',\n        \'EMAIL\',\n        \'TELEFONO\',\n        \'OPCION_UNICA\',\n        \'OPCION_MULTIPLE\')',
  `opciones` JSON NULL,
  PRIMARY KEY (`idCampo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultura`.`Integrantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`Integrantes` (
  `idUsuario` INT NOT NULL,
  `idActor` INT NOT NULL,
  `rol` VARCHAR(45) NOT NULL DEFAULT 'Dueño',
  `esDueño` TINYINT NOT NULL,
  PRIMARY KEY (`idUsuario`, `idActor`),
  INDEX `fk_Usuarios_has_Actores_Actores1_idx` (`idActor` ASC) VISIBLE,
  INDEX `fk_Usuarios_has_Actores_Usuarios1_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_has_Actores_Usuarios1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `cultura`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_has_Actores_Actores1`
    FOREIGN KEY (`idActor`)
    REFERENCES `cultura`.`Actores` (`idActor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultura`.`ModeradoresCategorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`ModeradoresCategorias` (
  `idCategoria` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idCategoria`, `idUsuario`),
  INDEX `fk_Categorias_has_Usuarios_Usuarios1_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_Categorias_has_Usuarios_Categorias1_idx` (`idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Categorias_has_Usuarios_Categorias1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `cultura`.`Categorias` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Categorias_has_Usuarios_Usuarios1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `cultura`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultura`.`Convocatorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`Convocatorias` (
  `idConvocatoria` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(145) NOT NULL,
  `descripcion` VARCHAR(445) NOT NULL,
  `fechaCreacion` DATETIME NOT NULL,
  `fechaCierre` DATETIME NOT NULL,
  PRIMARY KEY (`idConvocatoria`),
  UNIQUE INDEX `titulo_UNIQUE` (`titulo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultura`.`Formularios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`Formularios` (
  `idCategoria` INT NOT NULL,
  `idCampo` INT NOT NULL,
  `orden` INT NOT NULL,
  `esObligatorio` TINYINT NOT NULL,
  `esPublico` TINYINT NOT NULL,
  `estado` ENUM('A', 'I') NOT NULL DEFAULT 'A',
  PRIMARY KEY (`idCategoria`, `idCampo`),
  INDEX `fk_Categorias_has_CamposFormularios_CamposFormularios1_idx` (`idCampo` ASC) VISIBLE,
  INDEX `fk_Categorias_has_CamposFormularios_Categorias1_idx` (`idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Categorias_has_CamposFormularios_Categorias1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `cultura`.`Categorias` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Categorias_has_CamposFormularios_CamposFormularios1`
    FOREIGN KEY (`idCampo`)
    REFERENCES `cultura`.`CamposFormulario` (`idCampo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultura`.`RespuestasCampo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`RespuestasCampo` (
  `idCampo` INT NOT NULL,
  `idActor` INT NOT NULL,
  `valor` JSON NOT NULL,
  PRIMARY KEY (`idCampo`, `idActor`),
  INDEX `fk_CamposFormularios_has_Actores_CamposFormularios1_idx` (`idCampo` ASC) VISIBLE,
  INDEX `fk_RespuestasCampo_Actores1_idx` (`idActor` ASC) VISIBLE,
  CONSTRAINT `fk_CamposFormularios_has_Actores_CamposFormularios1`
    FOREIGN KEY (`idCampo`)
    REFERENCES `cultura`.`CamposFormulario` (`idCampo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RespuestasCampo_Actores1`
    FOREIGN KEY (`idActor`)
    REFERENCES `cultura`.`Actores` (`idActor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultura`.`FormulariosSubcategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`FormulariosSubcategoria` (
  `idCampo` INT NOT NULL,
  `idSubcategoria` INT NOT NULL,
  `idCategoria` INT NOT NULL,
  `orden` INT NOT NULL,
  `esObligatorio` TINYINT NOT NULL,
  `esPublico` TINYINT NOT NULL,
  `estado` ENUM('A', 'I') NOT NULL,
  PRIMARY KEY (`idCampo`, `idSubcategoria`, `idCategoria`),
  INDEX `FK_Subcategorias_idSubcategoria2_idx` (`idSubcategoria` ASC, `idCategoria` ASC) VISIBLE,
  INDEX `FK_CamposFormularios_idCampo1_idx` (`idCampo` ASC) VISIBLE,
  CONSTRAINT `FK_CamposFormularios_idCampo1`
    FOREIGN KEY (`idCampo`)
    REFERENCES `cultura`.`CamposFormulario` (`idCampo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Subcategorias_idSubcategoria2`
    FOREIGN KEY (`idSubcategoria` , `idCategoria`)
    REFERENCES `cultura`.`Subcategorias` (`idSubcategoria` , `idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultura`.`Postulaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultura`.`Postulaciones` (
  `idConvocatoria` INT NOT NULL,
  `idActor` INT NOT NULL,
  `fechaPostulacion` DATETIME NOT NULL,
  PRIMARY KEY (`idConvocatoria`, `idActor`),
  INDEX `FK_Convocatorias_idConvocatoria1_idx` (`idConvocatoria` ASC) VISIBLE,
  INDEX `fk_Postulaciones_Actores1_idx` (`idActor` ASC) VISIBLE,
  CONSTRAINT `FK_Convocatorias_idConvocatoria1`
    FOREIGN KEY (`idConvocatoria`)
    REFERENCES `cultura`.`Convocatorias` (`idConvocatoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Postulaciones_Actores1`
    FOREIGN KEY (`idActor`)
    REFERENCES `cultura`.`Actores` (`idActor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
