name: ESLint

# Controls when the workflow will run
on:
  push:
    paths:
      - "Codigo/**"
      - ".github/workflows/**"

jobs:
  eslint:
    # The type of runner that the job will run on
    runs-on: ubuntu-slim
    timeout-minutes: 10

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v6

      - uses: actions/setup-node@v7
        with:
          node-version: "lts/*"

      - name: npm ci frontend
        run: |
          cd "${GITHUB_WORKSPACE}"/Codigo/frontend || exit 1
          npm ci

      - name: npm ci backend
        run: |
          cd "${GITHUB_WORKSPACE}"/Codigo/backend || exit 1
          npm ci

      - name: ESLint y tsc
        run: |
          fracaso=0

          echo "🏁🏁🏁🏁🏁 Lint backend 🤖"
          cd "${GITHUB_WORKSPACE}"/Codigo/backend || exit 2
          if ! npm run lint; then
            echo "❌ Error en Lint backend 😢"
            fracaso=1
          fi

          echo "🏁🏁🏁🏁🏁 Build backend 🍇"
          cd "${GITHUB_WORKSPACE}"/Codigo/backend || exit 3
          if ! npm run build; then
            echo "❌ Error en Build backend 😞"
            fracaso=1
          fi

          echo "🏁🏁🏁🏁🏁 Lint frontend 🚀"
          cd "${GITHUB_WORKSPACE}"/Codigo/frontend || exit 4
          if ! npm run lint; then
            echo "❌ Error en Lint frontend 😔"
            fracaso=1
          fi

          echo "🏁🏁🏁🏁🏁 Build frontend 🛠️"
          cd "${GITHUB_WORKSPACE}"/Codigo/frontend || exit 5
          if ! npm run build; then
            echo "❌ Error en Build frontend 😟"
            fracaso=1
          fi

          if [ ${fracaso} -eq 1 ]; then
            echo "Se encontraron errores en el código 😱"
            exit 1
          else
            echo "Tudo bom, tudo legal 🌟✨"
          fi
